# -*- coding: utf-8 -*-
"""Travel review Rating.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whIk-wpM6ck4hHgPSXoWpPvFzDGxHf-m
"""

import pandas as pd
from google.colab import files
file1=files.upload()

data = pd.read_csv("/content/google_review_ratings.csv")

column_names = ['user_id', 'churches', 'resorts', 'beaches',
                'parks', 'theatres', 'museums', 'malls', 'zoo',
                'restaurants', 'pubs_bars', 'local_services',
                'burger_pizza_shops', 'hotels_other_lodgings',
                'juice_bars', 'art_galleries', 'dance_clubs',
                 'swimming_pools', 'gyms', 'bakeries', 'beauty_spas',
                'cafes', 'view_points', 'monuments', 'gardens', 'Unnamed: 25']

data.columns = column_names

data.info()

data.head()

data.isnull().sum()

pd.set_option('display.max_columns', 30)
data.describe()

import matplotlib.pyplot as plt
import warnings
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'


column_names = ['churches', 'resorts', 'beaches', 'parks', 'theatres', 'museums', 'malls', 'zoo',
                'restaurants', 'pubs_bars', 'local_services',
                'burger_pizza_shops', 'hotels_other_lodgings', 'juice_bars', 
                'art_galleries', 'dance_clubs', 'swimming_pools',
                'gyms', 'bakeries', 'beauty_spas', 'cafes', 'view_points', 'monuments', 'gardens']



counts = data[column_names[:]].astype(bool).sum(axis=0).sort_values()

test = []
for i in range(len(counts.index)):
    test.append(counts.index[i])
    



fig = px.bar(counts, 
             x=counts, 
             y=test,
             color=counts,
                             labels={
                     "total ratings": "this is x",
                     "categories": "this is y)"
                 },
                height = 800,
                title="Number of reviews under each category")

fig.show()

avg_rating = data[column_names[:]].mean().sort_values()



fig = px.bar(avg_rating,
            x = avg_rating.index,
            y = avg_rating.values,
            color = avg_rating.values,
            height = 800,
            title = "Average rating for each category")

fig.show()